/**
 * SpotCamp ID - Campsite Booking Platform API
 *
 * Contact: api@spotcamp.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BundleRequestComponentsInner } from './bundleRequestComponentsInner';


export interface BundleRequest { 
    name?: string;
    bundlePrice?: number;
    components?: Array<BundleRequestComponentsInner>;
}

