/**
 * SpotCamp ID - Campsite Booking Platform API
 *
 * Contact: api@spotcamp.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BundleComponent } from './bundleComponent';


export interface BundleResponse { 
    id?: number;
    name?: string;
    bundlePrice?: number;
    components?: Array<BundleComponent>;
}

