/**
 * SpotCamp ID - Campsite Booking Platform API
 *
 * Contact: api@spotcamp.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { BundleResponse } from './bundleResponse';


export interface BundleListResponse { 
    content?: Array<BundleResponse>;
    page?: PageMetadata;
}

