/**
 * SpotCamp ID - Campsite Booking Platform API
 *
 * Contact: api@spotcamp.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AmenityResponse } from './amenityResponse';
import { CampsiteImageResponse } from './campsiteImageResponse';


export interface CampsiteDetailResponse { 
    id?: number;
    name?: string;
    description?: string;
    status?: string;
    latitude?: number;
    longitude?: number;
    images?: Array<CampsiteImageResponse>;
    amenities?: Array<AmenityResponse>;
    rules?: Array<string>;
}

