/**
 * SpotCamp ID - Campsite Booking Platform API
 *
 * Contact: api@spotcamp.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CampsiteRequest { 
    name: string;
    description?: string;
    latitude: number;
    longitude: number;
    address?: string;
    phone?: string;
}

