/**
 * SpotCamp ID - Campsite Booking Platform API
 *
 * Contact: api@spotcamp.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { CampsiteResponse } from './campsiteResponse';


export interface CampsiteListResponse { 
    content?: Array<CampsiteResponse>;
    page?: PageMetadata;
}

