/**
 * SpotCamp ID - Campsite Booking Platform API
 *
 * Contact: api@spotcamp.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductRequest { 
    name: string;
    type: ProductRequest.TypeEnum;
    basePrice: number;
    description?: string;
    stockTotal?: number;
    dailyRate?: number;
    currentStock?: number;
    unitPrice?: number;
}
export namespace ProductRequest {
    export const TypeEnum = {
        RentalSpot: 'RENTAL_SPOT',
        RentalItem: 'RENTAL_ITEM',
        Sale: 'SALE'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}

