/**
 * SpotCamp ID - Campsite Booking Platform API
 *
 * Contact: api@spotcamp.id
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AmenityResponse } from './amenityResponse';


export interface UpdateCampsiteAmenities200Response { 
    amenities?: Array<AmenityResponse>;
}

